name: Create Release

on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'     
        required: true
        default: 'warning'
      tags:
        required: true
        description: 'Test scenario tags'  

jobs:

  build:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.15
    - name: Generate CLI Build
      run: |
          go build -o dist/crda
    - name: Archive production artifacts
      uses: actions/upload-artifact@v2
      with:
        name: crda
        path: |
          dist
