name: Create Release

on:
  push:
    branches: [ dk-action ]
  pull_request:
    branches: [ dk-action ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.15

    - name: Build
      run: go build -o crda 

    - name: Generate CLI Build
      run: |
          go build -o dist/crda
    - name: Archive production artifacts
      uses: actions/upload-artifact@v2
      with:
        name: crda
        path: |
          dist
